/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dataClassDestruct

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class CarTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Car()
        val trabbi = CarData(4, "601")
        assertEquals(classUnderTest.printCar(trabbi), "wheels: 4 - model: 601 ")
    }
}
